CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (
    "type" VARCHAR(10), "region" VARCHAR(10), 
    "state" VARCHAR(2), "store-id" INTEGER, 
    kpi_1_sum INTEGER, kpi_2_sum INTEGER, 
    kpi_3_sum INTEGER, kpi_4_sum INTEGER, 
    kpi_5_sum INTEGER,
    ingest_time TIMESTAMP);

CREATE OR REPLACE PUMP "STREAM_PUMP_REGION" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM UPPER('BY_REGION'), "region", UPPER('NN'), -1, 
    SUM("kpi-1") AS kpi_1_sum, SUM("kpi-2") AS kpi_2_sum, 
    SUM("kpi-3") AS kpi_3_sum, SUM("kpi-4") AS kpi_4_sum, 
    SUM("kpi-5") AS kpi_5_sum, 
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE) as ingest_time
FROM "SOURCE_SQL_STREAM_001"
GROUP BY UPPER('BY_REGION'), "region",
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE), 
    FLOOR(("SOURCE_SQL_STREAM_001".ROWTIME - TIMESTAMP '1970-01-01 00:00:00') SECOND / 10 TO SECOND);
    
CREATE OR REPLACE PUMP "STREAM_PUMP_STATE" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM UPPER('BY_STATE'), "region", "state", -1, 
    SUM("kpi-1") AS kpi_1_sum, SUM("kpi-2") AS kpi_2_sum, 
    SUM("kpi-3") AS kpi_3_sum, SUM("kpi-4") AS kpi_4_sum, 
    SUM("kpi-5") AS kpi_5_sum, 
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE) as ingest_time
FROM "SOURCE_SQL_STREAM_001"
GROUP BY UPPER('BY_STATE'), "region", "state",
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE), 
    FLOOR(("SOURCE_SQL_STREAM_001".ROWTIME - TIMESTAMP '1970-01-01 00:00:00') SECOND / 10 TO SECOND);

CREATE OR REPLACE PUMP "STREAM_PUMP_STORE" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT STREAM UPPER('BY_STORE'), "region", "state", "store-id", 
    SUM("kpi-1") AS kpi_1_sum, SUM("kpi-2") AS kpi_2_sum, 
    SUM("kpi-3") AS kpi_3_sum, SUM("kpi-4") AS kpi_4_sum, 
    SUM("kpi-5") AS kpi_5_sum,
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE) as ingest_time
FROM "SOURCE_SQL_STREAM_001"
GROUP BY UPPER('BY_STORE'), "region", "state", "store-id", 
    FLOOR("SOURCE_SQL_STREAM_001".APPROXIMATE_ARRIVAL_TIME TO MINUTE), 
    FLOOR(("SOURCE_SQL_STREAM_001".ROWTIME - TIMESTAMP '1970-01-01 00:00:00') SECOND / 10 TO SECOND);